--------------------------------------------------------
-----------------------  Variables  --------------------
--------------------------------------------------------

name: Variables
########################  Paths to use  ###############################

# Raw data path: where to find the raw data ?
raw_data_path: "/shared/projects/pacobar/archive/rawfile/"

# Folder where all the temporary files will be stored
tmp_path: "/shared/scratch/pacobar/bpajot/tmp/Processing_of_short_read_data/"

# Where to save the final output data
output_path: "/shared/projects/pacobar/finalresult/Littorina_WGS_illumina/SNP_calling/"
# Where is the reference genome
Reference_genome: "/shared/projects/pacobar/input/reference/Reference_Littorina_saxatilis_reshape.fa"



########################  Cut chromosomes  ###############################
# We need to break the chromosomes in the analysis into bins of a given size to be able to parallelise on the 
# chosen bins. To do so, we use this parameter (bin_size) to have the maximum number of bases in the chromosomal bins
# The default value in the function that cuts the chromosomes into bins is 1e6, but this parameter can be changed
bin_size: 1e7

########################  Missing rate  ###############################
# We need to use a missing data threshold value on the final vcf. The chosen value (between 0 and 1) will be used as 
# a maximum of missing data. For axample if you choose 0.95, only data with less than 5% of missing data will be kept
missing_rate: 0.95


---------------------------------------------------------
-----------------------  Profile  -----------------------
---------------------------------------------------------
name: Profile
########################  Cluster identification  ###############################
cluster:
  mkdir -p /shared/home/bpajot/fabalis/script/Littorina_WGS_illumina/Snakemake_SNP_calling/logs/{rule}/error_files/ &&
  mkdir -p /shared/home/bpajot/fabalis/script/Littorina_WGS_illumina/Snakemake_SNP_calling/logs/{rule}/logs/ &&
  sbatch
    --account=pacobar
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name={rule}-{wildcards}
    --output=/shared/home/bpajot/fabalis/script/Littorina_WGS_illumina/Snakemake_SNP_calling/logs/{rule}/logs/{rule}-{wildcards}-%j.out
    --error=/shared/home/bpajot/fabalis/script/Littorina_WGS_illumina/Snakemake_SNP_calling/logs/{rule}/error_files/{rule}-{wildcards}-%j.err
    --parsable

########################  Resources to use  ###############################
default-resources:
  - partition=fast
  - mem_mb=8000

########################  Parameters to use for the snakemake  ###############################
retries: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
cores: 40
jobs: 40
latency-wait: 60
keep-going: True
rerun-incomplete: True
printshellcmds: True
use-conda: True



---------------------------------------------------------
---------------------  Environments  --------------------
---------------------------------------------------------
name: Environments
########################  Dependencies  ###############################
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - fastqc = 0.12.1
  - multiqc = 1.13
  - fastp = 0.23.1
  - samtools = 1.15.1
  - bwa = 0.7.17
  - bcftools = 1.16
  - vcftools = 0.1.16
  # R and R packages
  - r = 4.3.1
  - r-pacman
  - r-tidyverse = 2.0.0
  - r-argparse
  - r-ggpubr
