cluster:
  mkdir -p /shared/projects/pacobar/finalresult/bpajot/logs/{rule}/error_files/ &&
  mkdir -p /shared/projects/pacobar/finalresult/bpajot/logs/{rule}/logs/ &&
  sbatch
    --account=pacobar
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name={rule}-{wildcards}
    --output=/shared/projects/pacobar/finalresult/bpajot/logs/{rule}/logs/{rule}-{wildcards}-%j.out
    --error=/shared/projects/pacobar/finalresult/bpajot/logs/{rule}/error_files/{rule}-{wildcards}-%j.err
    --parsable
default-resources:
  - partition=fast
  - mem_mb=8000
restart-times: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 10
jobs: 40
keep-going: True
rerun-incomplete: True
printshellcmds: True
use-conda: True
